enable-magisk-update = true
parallel-jobs = 1

[YouTube]
enabled = true
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX"
version = "auto"
build-mode = "module"
arch = "arm64-v8a"
riplib = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
